name: qless_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  http: ^1.2.0
  cached_network_image: ^3.3.1
  google_fonts: ^6.2.1
  camera: ^0.10.5+9
  shared_preferences: ^2.5.5
  supabase_flutter: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - inventory.json
  fonts:
    - family: ClashDisplay
      fonts:
        - asset: assets/fonts/ClashDisplay-Regular.ttf
        - asset: assets/fonts/ClashDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/ClashDisplay-Bold.ttf
          weight: 700
    - family: ClashGrotesk
      fonts:
        - asset: assets/fonts/ClashGrotesk-Regular.ttf
        - asset: assets/fonts/ClashGrotesk-Medium.ttf
          weight: 500
        - asset: assets/fonts/ClashGrotesk-Bold.ttf
          weight: 700
